sygmaprotocol/sygma-solidity

- .github/workflows/publish-contracts.yml
Refactor publish GitHub action to publish the package to the npm registry.
I added the `NPM_TOKEN` secret to this repository.
> Change publish-contracts pipeline to npm registry

- contracts/handlers/FeeHandlerRouter.sol
- contracts/handlers/fee/BasicFeeHandler.sol
- contracts/handlers/fee/FeeHandlerWithOracle.sol
This PR removes the redundant ABI coder v2 pragma since [ABI coder v2 is activated by default in Solidity v0.8.0](https://docs.soliditylang.org/en/v0.8.13/080-breaking-changes.html#silent-changes-of-the-semantics). 
> ABI coder v2 is activated by default.
>
> You can choose to use the old behaviour using pragma abicoder v1;. The pragma pragma experimental ABIEncoderV2; is still valid, but it is deprecated and has no effect. If you want to be explicit, please use pragma abicoder v2; instead.
>
> Note that ABI coder v2 supports more types than v1 and performs more sanity checks on the inputs. ABI coder v2 makes some function calls more expensive and it can also make contract calls revert that did not revert with ABI coder v1 when they contain data that does not conform to the parameter …
> Remove redundant ABIEncoderV2 pragma

- contracts/TestContracts.sol
For consistency, this PR uses double quote for string literals.
> Use double quote for string literals

- .github/workflows/publish-contracts.yml
- package.json
- truffle-config.js
Some minor fixes to contracts. 
Needed to build docker images for new local setup and deploy contracts via new migrations.
> Release 1.0.1

- .github/workflows/publish-contracts.yml
> Run truffle with npx

- .github/workflows/publish-contracts.yml
- package.json
> Release 1.0.2

- truffle-config.js
> Increase deploy timeout

- .github/workflows/publish-contracts.yml
Deploy on CI for Mumbai is too slow and either fails on timeout or it deploys for couple of hours and then timeouts.
Locally it is for whatever reason faster so we will go with that approach for now.
> Remove deploy from CI

- migrations/networks_config.json
- package.json
- truffle-config.js
Change local network chain IDs to prevent bugs with metamask.
> Update local test network chain IDs

- contracts/TestContracts.sol
- contracts/handlers/GenericHandlerV1.sol
- test/helpers.js
This introduces dynamic length params for GenericHandler (chain agnostic data format)
Closes: #67 
Unit tests
> Introduce chain agnostic data fromat for Generic handler

- migrations/local.json
The configuration for test2 network throws exception because access control configuration is invalid.
> Fix test2 network local.json configuration

- contracts/handlers/fee/FeeHandlerWithOracle.sol
- test/handlers/fee/withOracle/calculateFee.js
- test/handlers/fee/withOracle/collectFee.js
- test/handlers/fee/withOracle/distributeFee.js
- test/helpers.js
Add `msgGasLimit` to oracle message for calculating fees for premissionless generic handler.
Closes: #71 
Unit tests
> Add `msgGasLimit` param to `FeeHandlerWithOracle` message

- package.json
Add interfaces contracts to npm registry so they can be imported from the package.
> Add interfaces contracts to npm registry

- .github/workflows/test.yml
- Makefile
- scripts/generateFuncSignatures.js
- test/gasBenchmarks/deployments.js
- test/helpers.js
Add function that generates function signatures for Bridge contract functions wiht  `onlyAllowed` modifier.
Closes: #83 
- manual tests
- existing unit and e2e tests
> feat: add function for generating function signatures

- migrations/local.json
Add third domain to local.json
Added third domain that is necessary for substrate integration tests
manually
> chore: add third domain to local.json

- .github/workflows/publish-contracts.yml
> chore: remove publish workflow dependecy

- contracts/handlers/fee/BasicFeeHandler.sol
This PR fixes the typo: `amonuts` -> `amounts`
> chore: fix typo `amonuts` -> `amounts`

- contracts/handlers/ERC1155Handler.sol
This PR removes unused return variables in `ERC1155Handler.sol`: 
- `metaData`
> fix: remove unused return variable

- contracts/handlers/ERC1155Handler.sol
This PR removes the unused private state variable in `ERC1155Handler.sol`:
- `_INTERFACE_ERC1155_METADATA `
> fix: remove unused state var

- .eslintrc.js
- .github/workflows/publish-contracts.yml
- rollup.config.js
> chore: fix npm package build

- .github/workflows/publish-contracts.yml
> chore: fix package tags

- contracts/handlers/ERC1155Handler.sol
- contracts/handlers/ERC20Handler.sol
- contracts/handlers/ERC721Handler.sol
- contracts/handlers/ERCHandlerHelpers.sol
- contracts/handlers/PermissionedGenericHandler.sol
- contracts/handlers/XC20Handler.sol
- contracts/interfaces/IHandler.sol
- test/contractBridge/admin.js
- test/handlers/erc1155/depositBurn.js
- test/handlers/erc1155/isBurnable.js
- test/handlers/erc20/constructor.js
- test/handlers/erc20/depositBurn.js
- test/handlers/erc20/isBurnable.js
- test/handlers/erc20/isWhitelisted.js
- test/handlers/erc20/setResourceIDAndContractAddress.js
- test/handlers/erc721/depositBurn.js
- test/handlers/erc721/isBurnable.js
- test/handlers/generic/constructor.js
- test/handlers/xc20/constructor.js
- test/handlers/xc20/depositBurn.js
- test/handlers/xc20/isBurnable.js
- test/handlers/xc20/isWhitelisted.js
- test/handlers/xc20/setResourceIDAndContractAddress.js
- test/helpers.js
Introduces `ERCTokenContractProperties/TokenContractProperties` structs that store all contracts data in one mapping instead of multiple mappings .
Closes: #110
Unit tests, e2e tests
> chore: contract storage optimization

- contracts/handlers/fee/DynamicERC20FeeHandlerEVM.sol
- contracts/handlers/fee/DynamicERC20FeeHandlerSubstrate.sol
- test/handlers/fee/dynamic/calculateFeeERC20Substrate.js
Improve fee variable name on substrate handler
Closes: #144
> chore: rename finalFee to inclusionFee on substrate handler

- .github/workflows/publish-contracts.yml
Removes redundant release from CI
> fix: remove redundant release

- README.md
- docs/migrations.md
Provide more information on environment configuration - as currently, whoever executes migration scripts needs to know the nuances of our scripts to understand how to define environment configuration.
This PR is related to [#117](https://github.com/sygmaprotocol/project-backlog/issues/117) as it provides more context for someone executing migration scripts.
> chore: add description of environment configuration to README file

- package.json
- truffle-config.js
> chore: change test2 RPC url

- contracts/handlers/ERCHandlerHelpers.sol
Sets `view` mutability on conversion functions in `ERCHandlerHelpers` contract.
Closes: #172 
manual reviews
> fix: set mutability on conversion helper functions

- contracts/handlers/fee/DynamicFeeHandler.sol
- test/handlers/fee/dynamic/admin.js
Emits appropriate events on fee oracle address and fee properties changes.
Closes: #173 
unit tests
> fix: emit appropriate events on dynamic fee handler changes

- contracts/handlers/ERC1155Handler.sol
- test/contractBridge/admin.js
Checks if provided token address supports `IERC1155`.
Closes: #177 
unit tests
> fix: implement IERC1155 support check

- contracts/Bridge.sol
- contracts/handlers/ERC1155Handler.sol
- contracts/handlers/ERC20Handler.sol
- contracts/handlers/ERC721Handler.sol
- contracts/handlers/PermissionedGenericHandler.sol
- contracts/handlers/PermissionlessGenericHandler.sol
- contracts/handlers/XC20Handler.sol
- contracts/interfaces/IHandler.sol
- test/contractBridge/executeProposalERC20.js
- test/contractBridge/executeProposalXC20.js
- test/contractBridge/executeProposals.js
- test/handlers/erc20/decimals.js
- test/handlers/generic/permissionedExecuteProposal.js
- test/handlers/generic/permissionlessExecuteProposal.js
Implements `handlerReponse` in `executeProposal` function which is passed to `ProposalExecution` event.
Closes: #166
> feat: implement handler response on proposal execution

- migrations/devnet.json
- migrations/mainnet.json
- migrations/testnet.json
Updated config files after latest re-deployments/deployments
> chore: update devnet, testnet & mainnet migrations config files

- migrations/2_deploy_contracts.js
Register fee handler router in migration script (this was removed by accident in this [PR](https://github.com/sygmaprotocol/sygma-solidity/pull/206))
> fix: set up fee handler router in migration

- package.json
> fix: name for percentage fee handler abi publishing

- contracts/FROSTKeygen.sol
- migrations/9_deploy_frostKeygen.js
- test/frostKeygen/frostKeygen.js
Added FROSTKeygen contract that emits an event for triggering FROST keygen on relayers. 
closes #226
> feat: Add FROSTKeygen contract and tests

- contracts/handlers/fee/BasicFeeHandler.sol
- contracts/handlers/fee/PercentageERC20FeeHandlerEVM.sol
- contracts/handlers/fee/V2/DynamicFeeHandlerV2.sol
- test/handlers/fee/basic/admin.js
- test/handlers/fee/percentage/admin.js
- testUnderForked/admin.js
Adds fee handler type prop to query fee handler type from other services.
Closes: #238 
unit test
> feat: add fee handler type prop

- contracts/handlers/fee/V2/DynamicERC20FeeHandlerEVMV2.sol
- contracts/handlers/fee/V2/DynamicFeeHandlerV2.sol
- contracts/handlers/fee/V2/DynamicGenericFeeHandlerEVMV2.sol
- testUnderForked/collectFeeERC20EVM.js
- testUnderForked/collectFeeGenericEVM.js
Added a revert when the destination coin's price was set to 0.
> fix: add zero check for price

- contracts/handlers/PermissionlessGenericHandler.sol
Refactored decoding in PermissionlessGenericHandler to improve readability of the code
Refactored decoding in PermissionlessGenericHandler to improve readability of the code
All the tests remained the same. All the tests pass.
> chore: refactor decoding in permissionless handler

- migrations/local.json
- migrations/utils.js
add btc to e2e test data
add btc to e2e test data
> chore: add btc to e2e test data

- contracts/FROSTKeygen.sol
- test/frostKeygen/frostKeygen.js
> fix: make frost keygen retryable

- contracts/adapters/nativeTokens/NativeTokenAdapter.sol
- contracts/handlers/FeeHandlerRouter.sol
- contracts/handlers/NativeTokenHandler.sol
- contracts/handlers/fee/BasicFeeHandler.sol
- contracts/interfaces/IBasicFeeHandler.sol
- contracts/interfaces/IBridge.sol
- test/adapters/native/collectFee.js
- test/adapters/native/decimalConversion.js
- test/adapters/native/deposit.js
- test/adapters/native/distributeFee.js
- test/adapters/native/executeProposal.js
- test/helpers.js
Adds adapter and native token handler (modifier erc20 handler) for native token transfers (intended to be used for BTC<>EVM)
Closes: #231
unit tests
> feat: add native token handler and adapter

- Makefile
- contracts/Retry.sol
- test/retry/retry.js
Add separate retry contract that is able to call retry on any network.
> feat: retry contract

- contracts/handlers/DefaultMessageReceiver.sol
- contracts/handlers/DepositDataHelper.sol
- contracts/handlers/ERC1155Handler.sol
- contracts/handlers/ERC20Handler.sol
- contracts/handlers/ERC721Handler.sol
- contracts/handlers/ERCHandlerHelpers.sol
- contracts/handlers/GmpHandler.sol
- contracts/handlers/NativeTokenHandler.sol
- contracts/handlers/XC20Handler.sol
- contracts/handlers/fee/BasicFeeHandler.sol
- contracts/handlers/fee/PercentageERC20FeeHandler.sol
- contracts/handlers/fee/dynamic/TwapFeeHandler.sol
- contracts/utils/SanityChecks.sol
- test/handlers/erc20/deposit.js
- test/handlers/xc20/deposit.js
- testUnderForked/collectFeeERC20EVM.js
- testUnderForked/collectFeeGenericEVM.js
All details will be added when internal discussions finalize.
#264 #265 
All the changes so far are covered by the exiting tests.
> chore: address Veridise findings
