sygmaprotocol/sygma-solidity

contracts/ERC1155Safe.sol

This PR fixes the typo: `custoday` -> `custody`.

Fix typo custoday -> custody

---

contracts/example/Colors.sol
contracts/handlers/GenericHandlerV1.sol
migrations/3_deploy_genericHandlerV1.js
migrations/4_deploy_colors_example.js
package.json
test/handlers/generic/colors_example/deposit.js
test/handlers/generic/colors_example/executeProposal.js
test/helpers.js

Use `Colors` contract to showcase `GenericHandlerV1` usage.
Closes: sygmaprotocol/project-backlog/#29
Unit tests

Add colors example for using generic handler v1

---

contracts/interfaces/IERC20Plus.sol
test/contractBridge/depositXC20.js
test/contractBridge/executeProposalXC20.js

* While testing [XC20 mint fix](https://github.com/sygmaprotocol/sygma-solidity/issues/116) I found `mint/burn` strategy for XC20 wasn't being tested properly (burnable was set only for first test, not all of them in `mint/burn` test suite).
* Also `mint/burn` definition in `IERC20Plus` shouldn't define return value.
- unit tests, e2e tests

fix: XC20 `mint/burn` tests

---

contracts/XC20Safe.sol
test/contractBridge/executeProposalXC20.js

As @mpetrun5 reported when using Precompile ERC20 contract on Astar, when `executeProposal` is triggered and handler (token issuer) tries to mint tokens to recipient it fails. On Astar token issuer can only mint tokens to himself.
Fixes minting tokens to recipient on `executeProposal`:
- first mint tokens to XC20Handler
- then transfer tokens to the recipient
Closes: #116 
Unit and e2e tests

fix: minting xc20 tokens when executing proposal

---

contracts/TestContracts.sol
contracts/handlers/ERCHandlerHelpers.sol
migrations/2_deploy_contracts.js
migrations/5_renounceAdmin.js
migrations/local.json
migrations/utils.js
test/e2e/erc20/decimals/bothChainsNot18Decimals.js
test/e2e/erc20/decimals/oneChainNot18Decimals.js
test/e2e/erc20/decimals/oneChainWith0Decimals.js
test/e2e/erc20/decimals/roundingLoss.js
test/handlers/erc20/decimals.js

* Remove `decimals` mapping and store those values in `_tokenContractAddressToTokenProperties` since it has the same key.
* Introduce ERC20 token with customizable decimals value for our testing envs, to have a more real life examples.
Closes: #138 
Unit tests and e2e tests

chore: improvements for ERC20 decimals values

---

migrations/6_redeploy_token_handlers.js
migrations/utils.js

Currently when redeploying and registering new handlers migration is executed it deploys and registers a new handler for each token.
Expected behaviour should be to deploy one token handler per network and register all belonging tokens to that handler.
Closes: #147
Manual tests

fix: deploy and register one token handler per network

---

migrations/utils.js

When migrating ERC20 handler set new handler as minter for tokens that use mint/burn strategy.
manual tests

fix: set new handler as minter

---

contracts/TestContracts.sol
contracts/handlers/PermissionlessGenericHandler.sol
test/handlers/generic/permissionlessDeposit.js
test/handlers/generic/permissionlessExecuteProposal.js
test/helpers.js

Currently `executionDataDepositor` address is decoded in `deposit` function on origin chain as `abi.decode` so its length is not used here and the address is read as 32 bytes (20 bytes padded with 0).
This change implements parsing of `executionDataDepositor` in the same way as `executeContractAddress`, using its length (20 bytes for EVM).
We had different encodings of `executionDataDepositor` and `executeContractAddress` addresses: one of them was encoded using 32 bytes and another one was encoded using 20 bytes (for EVM chains). This change would make the encoding consistent.
Unit tests were updated.

chore: PermissionlessGenericHandler: unpack depositor address with custom length

---

contracts/handlers/ERCHandlerHelpers.sol
test/contractBridge/admin.js
test/handlers/erc1155/isBurnable.js
test/handlers/erc20/isBurnable.js
test/handlers/erc721/isBurnable.js
test/handlers/xc20/isBurnable.js

Currently when a token is set as burnable this is irreversible, if we want to mark tokens as non burnable we have to redeploy the handler, withdraw all tokens from it and re-register all existing resource. This introduces the possibility to re-register resource and mark the toke as not burnable.
unit test
- [] I have ensured that all acceptance criteria (or expected behavior) from issue are met

chore: enable setting tokens as not burnable

---

contracts/Bridge.sol
test/handlers/generic/permissionedDeposit.js

Return (depositNonce, handlerResponse) from Bridge.deposit()
Bridge will return (depositNonce, handlerResponse) from Bridge.deposit(). The returned values could be used by external adapters that interact with the Bridge.
#163
Closes: #163
Unit tests

feat: return data from Bridge.deposit()

---

migrations/devnet.json
migrations/testnet.json

Adds configs for devnet and testnet so we have configs per environment and easily deploy/update them through migrations.
manual deployments

chore: add devnet and testnet configs for migrations

---

contracts/Bridge.sol
contracts/Forwarder.sol
contracts/Migrations.sol
contracts/TestContracts.sol
contracts/handlers/FeeHandlerRouter.sol
contracts/handlers/PermissionedGenericHandler.sol
contracts/handlers/PermissionlessGenericHandler.sol
contracts/handlers/fee/BasicFeeHandler.sol
contracts/utils/AccessControlSegregator.sol

Removes unnecessary `public` visibility from constructors, visibility for constructors has been deprecated.
Closes: #170 
manual review

fix: remove unnecessary visibility from constructors

---

contracts/Migrations.sol

Since `owner` variable is set in constructor and never changed set it as `immutable` to save on gas.
Closes: #176 
manual review

fix: set owner variable as immutable

---

contracts/ERC20Safe.sol
contracts/TestContracts.sol
contracts/XC20Safe.sol
test/contractBridge/executeProposalXC20.js
test/contractBridge/executeWithFailedHandler.js

Use `_safeTransfer()` insead of `transfer()` to prevent  failed transfers, but `mintERC20` successful.
Closes: #168 
unit tests

fix: check successful transfer when minting XC20 tokens

---

contracts/Bridge.sol
contracts/ERC20Safe.sol
contracts/TestContracts.sol
contracts/handlers/ERC1155Handler.sol
contracts/handlers/ERC20Handler.sol
contracts/handlers/ERC721Handler.sol
contracts/handlers/ERCHandlerHelpers.sol
contracts/handlers/PermissionedGenericHandler.sol
contracts/handlers/XC20Handler.sol
contracts/handlers/fee/BasicFeeHandler.sol
contracts/handlers/fee/DynamicERC20FeeHandlerEVM.sol
contracts/handlers/fee/DynamicERC20FeeHandlerSubstrate.sol
contracts/handlers/fee/DynamicFeeHandler.sol
contracts/handlers/fee/DynamicGenericFeeHandlerEVM.sol
test/contractBridge/admin.js
test/contractBridge/depositERC1155.js
test/contractBridge/depositERC20.js
test/contractBridge/depositERC721.js
test/contractBridge/depositGeneric.js
test/contractBridge/depositXC20.js
test/contractBridge/executeProposalERC20.js
test/contractBridge/executeProposalXC20.js
test/contractBridge/executeProposals.js
test/handlers/erc20/decimals.js
test/handlers/fee/basic/collectFee.js
test/handlers/fee/dynamic/calculateFeeERC20EVM.js
test/handlers/fee/dynamic/calculateFeeERC20Substrate.js
test/handlers/fee/dynamic/calculateFeeGenericEVM.js
test/handlers/fee/dynamic/collectFeeGenericEVM.js
test/helpers.js

Use `revert Custom Errro()` instead of `require` across contracts to reduce gas consumption.
Closes: #179 
unit tests

fix: use custom errors to reduce gas consumption

---

contracts/handlers/fee/BasicFeeHandler.sol
contracts/handlers/fee/PercentageERC20FeeHandler.sol
contracts/handlers/fee/PercentageERC20FeeHandlerEVM.sol
migrations/2_deploy_contracts.js
migrations/3_deploy_permissionlessGenericHandler.js
migrations/4_deploy_xc20_contracts.js
migrations/local.json
migrations/utils.js
package.json
test/handlers/fee/percentage/admin.js
test/handlers/fee/percentage/calculateFee.js
test/handlers/fee/percentage/changeFee.js
test/handlers/fee/percentage/collectFee.js
test/handlers/fee/percentage/distributeFee.js

Introduces new fee handler that charges % from the transferred token amount.
Closes: #188 
- unit tests

feat: percentage based fee handler

---

migrations/2_deploy_contracts.js
migrations/3_deploy_permissionlessGenericHandler.js

* Deploy by default `DynamicGenericFeeHandlerEVM` with `PermissionlessGenericHandler` and assign it as default fee handler
* Removes default deployment of `PermissionedGenericHandler`
* manual tests

chore: permission generic handlers

---

contracts/handlers/FeeHandlerRouter.sol
test/handlers/fee/handlerRouter.js

Implement a fee whitelist for admin set addresses to enable some protocols or users to avoid fees.
Closes: #202
- unit tests

feat: Implement fee whitelist

---

contracts/handlers/fee/BasicFeeHandler.sol
contracts/handlers/fee/PercentageERC20FeeHandlerEVM.sol
migrations/2_deploy_contracts.js
migrations/3_deploy_permissionlessGenericHandler.js
migrations/4_deploy_xc20_contracts.js
migrations/5_renounceAdmin.js
migrations/utils.js
test/handlers/fee/basic/admin.js
test/handlers/fee/basic/calculateFee.js
test/handlers/fee/basic/changeFee.js
test/handlers/fee/basic/collectFee.js
test/handlers/fee/basic/distributeFee.js
test/handlers/fee/handlerRouter.js
test/handlers/fee/percentage/admin.js
test/handlers/fee/percentage/calculateFee.js
test/handlers/fee/percentage/changeFee.js
test/handlers/fee/percentage/collectFee.js
test/handlers/fee/percentage/distributeFee.js

This introduces a mapping for fees per destination domain. Now we don't have to deploy a new handler for every fee amount, they all can be setup in a single basic/percentage fee handler.
Also removes setting up fees in migrations since now there would be too many moving parts to do it automatically. 
In general we need to rethink about fees and how to approach to migrations.
Closes: #205
Closes: #151
existing unit and e2e tests  are updated

feat: add support for different fees per dest domain to basic/percentage fee handler

---

contracts/FROSTKeygen.sol
test/frostKeygen/frostKeygen.js

Removed resourceID from FROSTKeygen contract and made it callable only once. 
closes #229

chore: Remove resourceID from FROSTKeygen contract

---

.github/workflows/test.yml
Makefile
contracts/handlers/FeeHandlerRouter.sol
contracts/handlers/fee/V2/DynamicERC20FeeHandlerEVMV2.sol
contracts/handlers/fee/V2/DynamicFeeHandlerV2.sol
contracts/handlers/fee/V2/DynamicGenericFeeHandlerEVMV2.sol
testUnderForked/calculateFeeERC20EVM.js
testUnderForked/collectFeeERC20EVM.js
testUnderForked/collectFeeGenericEVM.js

Extends the fee calculation formula with the option to charge on top of execution fee a protocol fee.
Protocol fee can be a fixed amount of native token or a percentage of the execution cost.
Closes: #242 
unit test

feat: extend fee calculation formula

---

contracts/handlers/FeeHandlerRouter.sol
contracts/handlers/fee/BasicFeeHandler.sol
contracts/handlers/fee/DynamicFeeHandler.sol
contracts/handlers/fee/PercentageERC20FeeHandlerEVM.sol
contracts/handlers/fee/V2/DynamicFeeHandlerV2.sol
contracts/interfaces/IFeeHandler.sol
test/handlers/fee/basic/admin.js
test/handlers/fee/dynamic/admin.js
test/handlers/fee/handlerRouter.js
test/handlers/fee/percentage/admin.js

Adds `feeHandlerType` getter to `IFeeHandler` 
unti tests

chore: extend IFeeHandler with feeHandlerType getter

---

package.json

* Dynamic generic fee handlers don't exist anymore (v1 dynamic fee handlers) - they are replaced with Twap fee handlers.
* Fixes typo for fee handler router because of which it didn't get published to npm.

chore: update what gets pushed to npm package

---

package.json

Fix cli commands for deploying local networks after migrating from `ganache-cli`  to `ganache`

fix: deploying local networks
